### ISSUE TITLE
iOS8以上系统使用库以后，keyboard不正常

### ISSUE THREAD

**Issue by whtoo** [youngsoft/MyLinearLayout#1]
具体表现是，keyboard的在做输入法切换的时候，会很慢很卡，而且，有时候keyboard会变成灰色的

**Comment by youngsoft** [comment]
您好！
  我做了一个实验，估计您是在模拟器上进行测试，IOS8的模拟器的键盘确实会有这个问题，跟这个库没有关系，而且我在真机上的IOS8上进行了测试发现没有出现您的这个问题，因为布局库是对键盘没有影响的。如果您有具体的截图请发送给我，或者具体在哪个地方使用出问题了也发送给我。




原始邮件
发件人:ShareArchnotifications@github.com
收件人:youngsoft/MyLinearLayoutMyLinearLayout@noreply.github.com
发送时间:2015年8月18日(周二) 13:58
主题:[MyLinearLayout] iOS8以上系统使用库以后，keyboard不正常 (#1)


具体表现是，keyboard的在做输入法切换的时候，会很慢很卡，而且，有时候keyboard会变成灰色的

**Comment by whtoo** [comment]
你好，请试试和pod依赖一起工作的工程的情况。pod里面加入reactivecocoa和masonry试试。

**Comment by whtoo** [comment]
![c3233f9badb31d2fb36472dcf2e43afc](https://cloud.githubusercontent.com/assets/909131/9324249/18972f7a-45bb-11e5-8e69-0ae9a690a69c.png)
![img_1046](https://cloud.githubusercontent.com/assets/909131/9324250/18d5b1e6-45bb-11e5-83a9-8ad0dbe5b3e6.PNG)

**Comment by whtoo** [comment]
异常的键盘截图 我的5s上的 去掉 mylinearlayout就好了
