### ISSUE TITLE
关于相对布局(MyRelativeLayout)子视图底部停靠的问题(还是个矛盾体)

### ISSUE THREAD

**Issue by szmichael-desgin** [youngsoft/MyLinearLayout#100]
### 视图原料
1. 根布局视图：MyRelativeLayout。下文称rootlayout。
2. 子布局视图：MyLinearLayout，2个。下文以 sub1 / sub2 简称之。

### 预期效果
使用MyRelativeLayout，想实现如下需求：
1. 2个线性子布局视图之间的最小间距 >= 50px;
2. sub1始终停靠在父布局视图顶部；sub2始终停靠在父布局视图底部20px;
3. 父布局视图的最小高度为屏幕高度。

### 实现代码
```objc
UIScrollView * scrollView = [UIScrollView new];
MyRelativeLayout * rootlayout = [MyRelativeLayout new];
DFTradePwdCaptView * tradeCaptView = [DFTradePwdCaptView tradePwdCapt:type target:self];
LoginCellView * hotCellV = [LoginCellView loginCell:self];
scrollView.showsVerticalScrollIndicator = NO;
scrollView.showsHorizontalScrollIndicator = NO;
scrollView.backgroundColor = ybColorFromHexRGB(0xF0F2F6);
scrollView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
tradeCaptView.myHorzMargin = 0;
tradeCaptView.myTop = 0;

CGFloat topM = MYDIMESCALE(50);
hotCellV.topPos.equalTo(tradeCaptView.bottomPos).min(topM).max(5 * topM);
hotCellV.myHorzMargin = 0;
hotCellV.myBottom = MYDIMESCALE(20);

rootlayout.myHorzMargin = 0;
rootlayout.heightSize.equalTo(rootlayout.heightSize).min(appData_.screenH - appData_.navBarH);
// rootlayout.wrapContentHeight = YES;

tradeCaptView.backgroundColor = ybBrownColor();
hotCellV.backgroundColor = ybBlueColor();
rootlayout.backgroundColor = ybRedColor();

self.tradeCaptView = tradeCaptView;
self.hotCellV = hotCellV;
self.view = scrollView;

[rootlayout addSubview:tradeCaptView];
[rootlayout addSubview:hotCellV];
[scrollView addSubview:rootlayout];
```

### 具体问题
1. 父布局视图(rootlayout)高度不能动态计算，始终为屏幕高度；
2. sub2的高度计算也不做正确：长屏幕手机上高度被拉伸，端木手机上高度被压缩。

### 问题效果展示

留意各布局视图的的区分颜色。

```
红色：rootlayout
棕色：sub1
蓝色：sub2
```

<img width="433" alt="问题效果01 " src="https://user-images.githubusercontent.com/54985131/64427861-c6ec3300-d0e4-11e9-8acb-1a43255e0ff3.png">

<img width="392" alt="问题效果02" src="https://user-images.githubusercontent.com/54985131/64427877-d8353f80-d0e4-11e9-9103-3f61cc3280df.png">

正常高度(需要预期的效果)：

<img width="411" alt="正常高度" src="https://user-images.githubusercontent.com/54985131/64427928-fa2ec200-d0e4-11e9-8635-3853f67b7b53.png">

**Comment by youngsoft** [comment]
您的问题已经在1.9.0beta版本中得到修复。
