### ISSUE TITLE
ScrollView的子线性视图设置MyGravity_Vert_Bottom时，高度计算问题

### ISSUE THREAD

**Issue by ZHJMrLu** [youngsoft/MyLinearLayout#102]
父视图为滚动视图，设置最大、最小高度；子视图为高度动态的线性视图，设置最小高度为滚动视图的最小高度，内容紧贴底部；当子视图内容超出最小高度时，子视图没有被撑起来！

**Comment by youngsoft** [comment]
您可以下载最新的1.9.0beta版本，这个版本修复了这个BUG。
