### ISSUE TITLE
相对布局的居中问题

### ISSUE THREAD

**Issue by kchtin** [youngsoft/MyLinearLayout#103]
在使用相对布局做 tableviewCell 根视图的时候, 并且 cell 自适应高度.

 UIImageView *picterView = UIImageView.alloc.init;
    picterView.mySize = CGSizeMake(120, 120);
    picterView.leftPos.equalTo(self.rootLayout.leftPos);
    picterView.topPos.equalTo(self.rootLayout.topPos);
    picterView.backgroundColor = UIColor.kt_debugColor;
    [self.rootLayout addSubview:picterView];
    
    UIImageView *stateView = UIImageView.alloc.init;
    stateView.centerXPos.equalTo(picterView.centerXPos);
    stateView.backgroundColor = UIColor.kt_debugColor;
    stateView.mySize = CGSizeMake(30, 20);
    [self.rootLayout addSubview:stateView];
    
    UILabel *themeLabel = Kt_UILabelMake(@"哈哈聊天", rgba(51, 51, 51, 1), 14, NSTextAlignmentLeft);
    themeLabel.centerXPos.equalTo(picterView.centerXPos);
    [self.rootLayout addSubview:themeLabel];
    
    stateView.centerYPos.equalTo(@[themeLabel.centerYPos.offset(10)]);

结果 stateView 和 themeLabel的 Y 计算错误.

**Comment by youngsoft** [comment]
您可以下载最新的1.9.0beta版本来解决您的问题。
