### ISSUE TITLE
布局视图动画最好增加一个扩展

### ISSUE THREAD

**Issue by szmichael-desgin** [youngsoft/MyLinearLayout#106]
很多场景，可能需要在动画执行完毕后需要做一些操作。所以最好加一个动画扩展。

![image](https://user-images.githubusercontent.com/54985131/69036105-21c4d380-0a20-11ea-8741-9a415b8b62aa.png)

扩展一个 block

![image](https://user-images.githubusercontent.com/54985131/69036122-2c7f6880-0a20-11ea-8dac-2f3a1f5fe8ab.png)

**Comment by youngsoft** [comment]
您可以在最新发布的1.9.0beta版本中使用最新提供的动画API:
```
-(void)layoutAnimationWithDuration:(NSTimeInterval)duration;
-(void)layoutAnimationWithDuration:(NSTimeInterval)duration options:(UIViewAnimationOptions)options completion:(void (^)(BOOL finished))completion;
```
