### ISSUE TITLE
cell自适应的问题

### ISSUE THREAD

**Issue by wzj583585700** [youngsoft/MyLinearLayout#107]
在cell上查看更多的时候，显示更多数据，点击收起的时候。设置MyVisibility_Gone 的时候，cell自适应

**Comment by youngsoft** [comment]
解决这个问题需要两方面处理：
1.因为tableviewcell是可以复用的，所以状态值不应该保存在视图层级。所以隐藏与否标志应该保存在模型数据上。
2.当你在cell上操作查看更多按钮时触发的MyVisibility_Gone的设置更改后，应该调用reloadData或者reloadData布局的cell才能激发重新布局以及重新算高，所以单独一个属性设置是无法改变cell的高度自适应的。

**Comment by wzj583585700** [comment]
我reloadData 了，还是收不回去

**Comment by youngsoft** [comment]
看我给您的回复：

1.除了要reload之外，而且不要让视图保存状态变量。具体情况如果还不清楚请加入QQ群：178573773 来详细交流。
