### ISSUE TITLE
建议提供Swift版本的Demo，便于快速上手

### ISSUE THREAD

**Issue by fhchina** [youngsoft/MyLinearLayout#11]

**Comment by youngsoft** [comment]
您好！


 我会尽快推出swift版本。请期待。






原始邮件
发件人:fhchinanotifications@github.com
收件人:youngsoft/MyLinearLayoutMyLinearLayout@noreply.github.com
发送时间:2016年3月1日(周二) 23:24
主题:[MyLinearLayout] 建议提供Swift版本的Demo，便于快速上手 (#11)

**Comment by youngsoft** [comment]
非常抱歉！因为各种原因swift版本一直后延。但是经过努力,昨天晚上发布了Swift版本:TangramKit, 您可以到https://github.com/youngsoft/TangramKit 中下载
