### ISSUE TITLE
TableViewCell中线性布局中嵌套weight=1的线性布局及宽度自适应的相对布局时，出现高度计算不准

### ISSUE THREAD

**Issue by Lhw921025** [youngsoft/MyLinearLayout#116]
MyLayout 1.9.0  
TableViewCell中线性布局中嵌套weight=1的线性布局及宽度自适应的相对布局时，出现高度计算不准
<img width="312" alt="demo" src="https://user-images.githubusercontent.com/19581484/71569152-0ca39000-2b08-11ea-8d35-0616b54f6ffb.png">

**Comment by youngsoft** [comment]
问题已经在1.9.8版本修复，请下载最新的版本。
