### ISSUE TITLE
子view在切换hidden的时候的动画显示

### ISSUE THREAD

**Issue by maimake** [youngsoft/MyLinearLayout#12]
貌似在动画方面上比较难控制，某个子View要hidden的时候，希望子View有自身的动画效果，同时祖先layout和兄弟layout都要有动画更新。不知道有没有现成的什么好方法？

**Comment by youngsoft** [comment]
您好！


 默认的情况下，虽然hidden的操作会引发重新布局，但是默认时hidden是不会有动画效果的。如果您要动画效果，最好是用myHeight = 0; 来实现动画，因为hidden是不知道您是想高度缩小呢？还是宽度缩小，还是高度和宽度都缩小。因此建议您用调整myHeight, myWidth的值来实现动画效果。要实现动画效果您可以借助MyBaseLayout的两个方法：


@property(nonatomic,copy) void (^beginLayoutBlock)();
@property(nonatomic,copy) void (^endLayoutBlock)();


来实现。比如：


MyXXXLayout *layout = xxxx;


subview1.myHeight = 0;
layout.beginLayoutBlock = ^{
   
    [UIView beginAnimations:nil context:nil];
    [UIView setAnimationDuration:0.4];
  };
 
 layout.endLayoutBlock = ^{
   
    [UIView commitAnimations];
   
  };


来实现动画。所有的属性修改都可以带上动画效果。建议您在DEMO中搜索beginLayoutBlock 关键在来看看动画的实现方式。






原始邮件
发件人:maimakenotifications@github.com
收件人:youngsoft/MyLinearLayoutMyLinearLayout@noreply.github.com
发送时间:2016年3月4日(周五) 16:48
主题:[MyLinearLayout] 子view在切换hidden的时候的动画显示 (#12)


貌似在动画方面上比较难控制，某个子View要hidden的时候，希望子View有自身的动画效果，同时祖先layout和兄弟layout都要有动画更新。不知道有没有现成的什么好方法？
