### ISSUE TITLE
关于相对布局居中的问题

### ISSUE THREAD

**Issue by weilLove** [youngsoft/MyLinearLayout#122]
我想在相对布局的父布局视图上布局A,B,C三个子视图，让A靠左，C靠右，B居中，而且限定B的最大宽度是C的左边减去A的右边，我设置了B的lBound和uBound，框架中默认是设置这两个之后，B是在最小边界和最大边界的中间显示，那么我设置B的myCenterX = 0就没有作用了，如果我想让B在父布局上居中，同时又约束最大边界和最小边界，该如何实现呢，其实约束B的最大宽度就可以，但是我A,C的宽度都是未知的，所以想通过约束边界实现

**Comment by youngsoft** [comment]
你既然希望B居中，然后又希望最大宽度是A和C之间的剩余空间。问题是当A和C的宽度不相等时，同时B又比较大时，那么B必然不是布局视图居中，而应该是在A,C之间居中呀。。也可能你的问题没有描述清楚。您可以加入到QQ群：178573773  来深入讨论您的需求。

**Comment by weilLove** [comment]
[self.titleLabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(self.containerView.mas_centerX);
        make.centerY.equalTo(self.backBtn.mas_centerY);
        make.left.mas_greaterThanOrEqualTo(self.backBtn.mas_right);
        make.right.mas_lessThanOrEqualTo(self.righItem.mas_left);
    }];
我用masnory这样布局能实现最终要的效果，我的需求是无论如何B都是在父布局中居中，同时还要使得B的最大宽度不超过C的左边和A的右边，用Masnory是设置left和right的最大最小值，使用MyLayout的话我该如何设置呢？也许我用相对布局实现不了，那么其他布局类型可以吗

**Comment by weilLove** [comment]
问题已解决，解决方案如下
<img width="851" alt="截屏2020-01-15下午9 35 12" src="https://user-images.githubusercontent.com/14228146/72438070-0cc9ae00-37df-11ea-80fd-514905539c1d.png">  
最终效果如下：
<img width="406" alt="截屏2020-01-15下午9 34 55" src="https://user-images.githubusercontent.com/14228146/72438101-1d7a2400-37df-11ea-8c3a-dfd87f1cee62.png">
解决方案是依靠最值约束中的宽度约束，正如代码中展示的那样，要想让B居中显示，需要先约束A，C，然后让B.widthSize.equalTo(@[A.widthSize, C.widthSize].myMaxSize).multiply(-2).add(父视图宽度-左右间距-B与A和C的间距和)，这里要注意的是-2，上述代码读起来就是:B的宽度=A与C宽度的最大值*-2+(父视图宽度-左右间距-B与A和C的间距和), 谢谢作者大大今天的帮助，这个库还有待认真学习，内容真的很好，在慢慢熟悉过渡，再开发功能就尝试接入了
