### ISSUE TITLE
这个库确实好用不过在用的时候发现了一个bug

### ISSUE THREAD

**Issue by CYZZ** [youngsoft/MyLinearLayout#13]
bug：在用线性布局的时候MyLinerLayout1和MyLinerLayout2都是使用水平线性布局，加入rootLayout（垂直线性布局）设置了边界属性。但是两个子线性布局会发生重叠现象。在这个两个线性布局中加入了中间量就正常了。可以试着把demo的： LLTest1ViewController 把中间的label去除同时把下面的线性布局改成水平布局就会发现bug在那。

**Comment by youngsoft** [comment]
您好！没有看明白您的表述，是否可以加我的QQ:156355113 在线交流。估计您提的问题是属性设置得不合理导致的。

**Comment by CYZZ** [comment]
已经明白了，其实是相关的属性设置，讲解的挺好的，关键是对这个布局的库了解的不够。所以还是先解读明白这个类库就能解决很多问题了。
