### ISSUE TITLE
flexOtherViewWidthWhenSubviewHidden

### ISSUE THREAD

**Issue by wzj583585700** [youngsoft/MyLinearLayout#132]
flexOtherViewWidthWhenSubviewHidden, flexOtherViewHeightWhenSubviewHidden,这两个属性没有啊

**Comment by youngsoft** [comment]
看来您是用很老的版本了，目前最新版本升级到了1.9.8了。这两个属性很早就失效了，您可以用子视图的visibility属性来设置某个子视图隐藏时是否占位的能力。
