### ISSUE TITLE
希望尽快推出swift版本

### ISSUE THREAD

**Issue by WangWeiHuawwh** [youngsoft/MyLinearLayout#14]
希望尽快推出swift版本

**Comment by youngsoft** [comment]
请稍后，正在写。

**Comment by youngsoft** [comment]
非常抱歉！因为各种原因swift版本一直后延。但是经过努力,昨天晚上发布了Swift版本:TangramKit, 您可以到https://github.com/youngsoft/TangramKit 中下载
