### ISSUE TITLE
内容布局，增加压缩功能

### ISSUE THREAD

**Issue by dev-yang** [youngsoft/MyLinearLayout#15]
根据内容布局后，往往会有大量的空白空间，可以通过算法进行重新计算和布局。http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2016/0422/4169.html
这是我搜到的一个安卓版的功能实现

**Comment by youngsoft** [comment]
非常好的建议！我会在下一个版本中实现压缩这个功能

**Comment by youngsoft** [comment]
您好！流式布局的内容压缩功能已经实现了，您可以通过autoArrange属性来完成，另外还支持了间距拉伸，内容拉伸等功能。
