### ISSUE TITLE
咨询MyFlexLayout在Cell动态高度中的用法

### ISSUE THREAD

**Issue by zouki90** [youngsoft/MyLinearLayout#155]
大佬你好，以下是我cell中的全部代码，我企图通过label的文本高度「动态」的撑开cell的高度。
<a href="https://sm.ms/image/HJvdtjBceoRgPuT" target="_blank"><img src="https://s2.loli.net/2023/11/14/HJvdtjBceoRgPuT.png" ></a>

<a href="https://sm.ms/image/H7j4Fg3JIkO2Lty" target="_blank"><img src="https://s2.loli.net/2023/11/14/H7j4Fg3JIkO2Lty.png" ></a>

<a href="https://sm.ms/image/I1i3OkhLamclGsA" target="_blank"><img src="https://s2.loli.net/2023/11/14/I1i3OkhLamclGsA.png" ></a>
得到的结果是：
<a href="https://sm.ms/image/I2VFY5btuocsAOU" target="_blank"><img src="https://s2.loli.net/2023/11/14/I2VFY5btuocsAOU.png" ></a>
_________________________________________________________________________________________________________________
现在我的2个问题是：
1.为什么右侧没有留下16的距离空间，是哪里写错了吗？
2.要想通过MyFlexLayout来实现Cell的动态高度，以上代码基本是最简了吗？我是不是掌握的姿势不对。
多谢指导。

**Comment by youngsoft** [comment]
1.这是因为你的rootView是距离列表或者屏幕左右分别有16的边距。但是你在systemLayoutSizeFittingSize中的targetSize的宽度是屏幕或者列表的宽度。所以你传递给rootView的systemLayoutSizeFittingSize方法时，targetSize的宽度应该要减去32才是正确的rootView的宽度。问题就在这里。

2.上面你的代码已经是高度自适应了，已经实现动态高度了。

**Comment by zouki90** [comment]
好的非常感谢大佬，我已经按照指示调整，现在已完全正常工作，谢谢。
