### ISSUE TITLE
在cell中添加的一个仿天猫淘宝首页的浮动布局,点击手势添加后无法调用到

### ISSUE THREAD

**Issue by bcrystalest** [youngsoft/MyLinearLayout#16]
MyFloatLayout *itemLayout = [MyFloatLayout floatLayoutWithOrientation:MyLayoutViewOrientation_Horz];
    [itemLayout setTarget:self action:@selector(handleTap)];

看到仿zaker新闻布局是这么写的,但是用在我这里就不行,是不是放在tableview的cell中就要用另外方法了?

**Comment by youngsoft** [comment]
不用的。你看看你的handleTap方法是不是没有定义参数？ 如果有应该改为@selector(handleTap:)。如果还有问题您可以加我qq：156355113进行交流。

**Comment by bcrystalest** [comment]
问题已经解决,感谢指导
