### ISSUE TITLE
线性布局中不能正常使用bringSubviewToFront

### ISSUE THREAD

**Issue by KeGao** [youngsoft/MyLinearLayout#17]
您的线性布局顺序应该是根据subviews里面的顺序来排列的 但有的时候 我希望在原来的线性布局顺序下 让界面上方的视图层级变到上层 现在我如果使用bringSubviewToFront,视图frame就会跑到线性布局最下面位置

**Comment by youngsoft** [comment]
你好。当你使用bringSubviewToFront方法的时候，实际上iOS系统内部就会动态的调整所有子视图的顺序，并且把你调用的这个子视图作为第一个子视图，所以就造成了你说的问题，这个并不是布局库的问题。不知道你的具体需求是如何？按理来说线性布局里面的子视图是不会重叠的，因此不需要你去调用bringSubviewToFront来调整顺序。您也可以加我qq:156355113来具体讨论您需求的解决方案。
