### ISSUE TITLE
UIScrollView  一页页滑动的的约束怎么加  我加了一页垂直线性布局滑不了了

### ISSUE THREAD

**Issue by WangBingQuan1992** [youngsoft/MyLinearLayout#18]
_bottom1 = [[UIScrollView alloc]initWithFrame:CGRectMake(0, CGRectGetMaxY(self.spaceView.frame), mScreenWidth , mScreenHeight - CGRectGetMaxY(self.spaceView.frame))];
      
        _bottom1.alwaysBounceVertical = YES;
        _bottom1.showsHorizontalScrollIndicator = YES;
        _bottom1.delegate =self;
        _bottom1.tag = 100;
        _bottom1.contentSize = CGSizeMake(self.view.width * 2,_bottom1.height);
        _bottom1.pagingEnabled = YES;
        
    
//        UIView * view = [[UIView alloc]initWithFrame:CGRectMake(0, 0, mScreenWidth, 300)];
//        view.backgroundColor  = [UIColor redColor];
//        [_bottom1 addSubview:view];
        
        MyLinearLayout *laScroll = [[MyLinearLayout alloc] initWithOrientation:MyLayoutViewOrientation_Vert];
        laScroll.backgroundColor = [UIColor redColor];
//        laScroll.backgroundColor =  [UIColor colorWithWhite:0.950 alpha:1.000];
        laScroll.myLeftMargin = 0;
        laScroll.myHeight = 300;
        laScroll.myWidth = 200;
        laScroll.wrapContentHeight = YES;
        [_bottom1 addSubview:laScroll];

**Comment by youngsoft** [comment]
我这边根据你的代码测试是可以垂直滑动的。就是不知道你要水平滑动还是垂直滑动。你可以加我QQ：156355113跟我交流。
