### ISSUE TITLE
根据数据进行布局界面， 数据改变后怎么刷新界面

### ISSUE THREAD

**Issue by qyfeng009** [youngsoft/MyLinearLayout#19]

**Comment by youngsoft** [comment]
您好！


 您的问题太过于模糊，数据改变后，假如要更新UILabel的数据的话，您可以设置完.text的属性后调用一次UILabel的sizeToFit方法。其他的则根据您实际的应用情况，该怎么刷新就怎么刷新，就像普通的更新视图一样。您可以加我QQ:156355113进行交流。






原始邮件
发件人:qyfeng009notifications@github.com
收件人:youngsoft/MyLinearLayoutMyLinearLayout@noreply.github.com
发送时间:2016年7月4日(周一) 13:58
主题:[youngsoft/MyLinearLayout] 根据数据进行布局界面， 数据改变后怎么刷新界面 (#19)
