### ISSUE TITLE
属性需要加前缀躲避库冲突

### ISSUE THREAD

**Issue by whtoo** [youngsoft/MyLinearLayout#2]
你好，我们项目有继承的库，库里面提供了UIview的top，left，right，width，height的快捷属性访问。
这样的话就会和mylayout提供的属性名冲突，建议给整个库的公开属性加前缀，比如ML之类的避免这个问题。

**Comment by youngsoft** [comment]
新版本已经实现名称的冲突了，请下载最新的版本。
