### ISSUE TITLE
boss swift版本呢

### ISSUE THREAD

**Issue by JsonWong87** [youngsoft/MyLinearLayout#20]

**Comment by youngsoft** [comment]
非常感谢支持。现在正在努力的开发swift版本中。这个月底一定能出来跟大家见面。

**Comment by youngsoft** [comment]
非常抱歉！因为各种原因swift版本一直后延。但是经过努力,昨天晚上发布了Swift版本:TangramKit, 您可以到https://github.com/youngsoft/TangramKit 中下载

**Comment by JsonWong87** [comment]
太棒了，谢谢，谢谢💪🏻💪🏻💪🏻




在2016年10月28日 09:45，欧阳大哥 写道:

非常抱歉！因为各种原因swift版本一直后延。但是经过努力,昨天晚上发布了Swift版本:TangramKit, 您可以到https://github.com/youngsoft/TangramKit 中下载
