### ISSUE TITLE
可以把开头的My换个有代表性的

### ISSUE THREAD

**Issue by Easyzhan** [youngsoft/MyLinearLayout#21]

**Comment by youngsoft** [comment]
您好！


 这个也确实有很多人提过，主要是因为这个已经有一定时间和人使用了，如果改名字的成本就很大了，但是我的swift版本就有一个全新的而且好听的名字，不过暂时保密。






原始邮件
发件人:仅此而已notifications@github.com
收件人:youngsoft/MyLinearLayoutMyLinearLayout@noreply.github.com
发送时间:2016年8月5日(周五) 09:24
主题:[youngsoft/MyLinearLayout] 可以把开头的My换个有代表性的 (#21)
