### ISSUE TITLE
貌似有内存泄漏

### ISSUE THREAD

**Issue by jianjianhao** [youngsoft/MyLinearLayout#22]
使用Xcode分析发现有leak
<img width="738" alt="518a439c-bb18-4a29-96bd-5d8465476dbc" src="https://cloud.githubusercontent.com/assets/12797357/17473787/fa6e4474-5d84-11e6-905d-108dcf9abcd5.png">

**Comment by youngsoft** [comment]
您好！


非常感谢您的测试。这个是没有问题的。看看.h里面的注释：


/**
*创建布局的曲线的路径。用户需要负责销毁返回的值。调用者可以用这个方法来获得曲线的路径，进行一些绘制的工作。
*subviewCount:指定这个路径上子视图的数量的个数，如果设置为-1则是按照布局视图的子视图的数量来创建。需要注意的是如果布局视图的spaceType为Flexed,Count的话则这个参数设置无效。
*/
-(CGPathRef)createPath:(NSInteger)subviewCount;




您需要对返回的路径对象进行释放操作。。






原始邮件
发件人:jianjianhaonotifications@github.com
收件人:youngsoft/MyLinearLayoutMyLinearLayout@noreply.github.com
发送时间:2016年8月8日(周一) 16:28
主题:[youngsoft/MyLinearLayout] 貌似有内存泄漏 (#22)


使用Xcode分析发现有leak
