### ISSUE TITLE
highlightedOpacity 属性 无效

### ISSUE THREAD

**Issue by tanranran** [youngsoft/MyLinearLayout#23]
建议内部的点击事件增加一种这样的，超级好用

https://github.com/jakemarsh/JMWhenTapped

**Comment by youngsoft** [comment]
是这样的，这个高亮属性是必须设置触摸事件后才有用，否则是没有意义的。所以你设置这个属性时，必须要同时设置setTarget方法来指定一个点击事件才可以。

**Comment by tanranran** [comment]
@youngsoft  好的
