### ISSUE TITLE
MyRelativeLayout 里面的offset和Masonry里面的offset 冲突，建议增加前缀

### ISSUE THREAD

**Issue by tanranran** [youngsoft/MyLinearLayout#24]

**Comment by youngsoft** [comment]
那是因为masonry的宏定义导致的，里面貌似有能解决冲突的宏定义。另外建议作者在两种布局里面二选一。

**Comment by tanranran** [comment]
@youngsoft  尝试过了，应为项目是老项目，所以里面有不少masonry的代码
目前只发现equalTo和offset这两个有冲突。
至于宏定义。masonry 确实有mas_offset和mas_equalTo，我也把masonry里面的全都换成了这两个
但是MyRelativeLayout 默认获取的还是masonry里面的equalTo和offset

**Comment by youngsoft** [comment]
不会把。我们现在也还有项目是两种布局混用的。没有出现你的问题。QQ交流吧：156355113

**Comment by youngsoft** [comment]
见V1.2.6中已经处理过了。
