### ISSUE TITLE
欧阳大哥 你好

### ISSUE THREAD

**Issue by Code4AppiOS** [youngsoft/MyLinearLayout#27]
非常希望您的github介绍文里，可以增加code4app的下载地址，希望您可以加上哦！

http://www.code4app.com/thread-7501-1-1.html

**Comment by youngsoft** [comment]
是这样的。code4app里面的代码只是其中的一个快照，不是最新的，所以最新版本还是建议到github上下载最新的版本。

**Comment by bacy** [comment]
要是能把类名里面My两个字去掉就好了，哈哈

**Comment by youngsoft** [comment]
非常感谢这个提议。这个是历史原因，估计去掉不大可能了，不过Swift版本叫TangramKit：https://github.com/youngsoft/TangramKit。 不过不要纠结这个命名了。MySQL不也是很强大吗？

不过后续的2.0有可能会对属性和方法名进行一些变更。
