### ISSUE TITLE
已有的工程中如何开始使用呢？

### ISSUE THREAD

**Issue by Lisa1900** [youngsoft/MyLinearLayout#28]
其实我在想 之前使用的xib 或纯代码约束实现的UI 然后刚刚看到这个sdk 感觉很强大，but 在已有的工程中如何开始使用呢？

**Comment by youngsoft** [comment]
非常感谢你的支持。这个对已经有的工程中的代码是不影响的。而且这个库是可以和XIB，SB，以及AutoLayout和masonry共用的。因此你放心的加入吧。你如果用POD则安装 MyLayout 1.2.9版本。或者你直接复制Lib下的文件到你的工程中就可以了。
