### ISSUE TITLE
问一下dynamic cell怎么设置最大和最小高度

### ISSUE THREAD

**Issue by Insofan** [youngsoft/MyLinearLayout#31]
想设置一个cell最大和最小的高度，其他情况随着label中text的内容大小变化

**Comment by youngsoft** [comment]
您可以这样，看我的AllTest1ViewController里面有关于介绍动态cell高度的使用方法。在cell中建立一个布局视图rootLayout,然后把rootLayout作为cell.contentView的子视图，然后设置rootLayout的高度自适应，然后设置高度的最小和最大值。具体代码如下：

MyXXXLayout rootLayout = [MyXXXXLayout new];
rootLayout.widthDime.equalTo(self.contentView.widthDime);
rootLayout.wrapContentHeight = YES;
rootLayout.heightDime.min(20).max(100);  //虽然高度包裹但是最大100，最小20
[self.contentView addSubview:rootLayout];

//...接下来您就可以使用尺寸评估的方法了。。。具体参见AllTest1ViewController
