### ISSUE TITLE
适配阿拉伯国家

### ISSUE THREAD

**Issue by FaDeve** [youngsoft/MyLinearLayout#33]
请问这个框架能做到适配阿拉波吗？就是界面从右向左布局，很希望能用上这个库！

**Comment by youngsoft** [comment]
非常感谢你的提议，因为对阿拉伯国家的从右往左的方式不是非常的了解，期望你能加我的QQ：156355113。 我们可以在QQ上即时交流，了解你的需求。。。

**Comment by youngsoft** [comment]
您好！
    经过一个多月的奋战，在新版本[V1.3.6](https://github.com/youngsoft/MyLinearLayout/releases/tag/1.3.6)中已经实现了对界面从右往左的布局的支持。新版本中增加了如下属性：

所属类名|新属性|等价于LRT方向布局|等价于RTL布局方向
-------|---------------|---------------|------------
UIView(MyLayoutExt)|leadingPos|leftPos|rightPos
UIView(MyLayoutExt)|trailingPos|rightPos|leftPos
UIView(MyLayoutExt)|myLeading|myLeft|myRight
UIView(MyLayoutExt)|myTrailing|myRight|myLeft
MyBaseLayout|leadingPadding|leftPadding|rightPadding
MyBaseLayout|trailingPadding|rightPadding|leftPadding
MyBaseLayout|leadingBorderline|leftBorderline|rightBorderline
MyBaseLayout|trailingBorderline|rightBorderline|leftBorderline
MyGravity|MyGravity_Horz_Leading|MyGravity_Horz_Left|MyGravity_Horz_Right
MyGravity|MyGravity_Horz_Trailing|MyGravity_Horz_Right|MyGravity_Horz_Left

这些属性分别描述头部和尾部。同时MyLayout提供了一个类属性：isRTL。当将这个属性设置为YES时，那么所有的布局都将从右往左，而当设置为NO时则所有的布局都将从左往右。具体您可以参考这个库中的各种DEMO的演示，以及参考文档。

**Comment by qyzhaojinxi** [comment]
很给力啊

**Comment by FaDeve** [comment]
确实牛逼
