### ISSUE TITLE
使用大哥这个库,发现了会有uilabel和uibutton文字虚化的问题

### ISSUE THREAD

**Issue by kchtin** [youngsoft/MyLinearLayout#37]
当设置一个uilabel或者uibutton的sizetofit( ||  wrapContentSize = yes)的时候,再添加到布局中,发现文字会有虚化模糊效果;

**Comment by youngsoft** [comment]
您好! 这个问题已经在新发布的[1.3.7](https://github.com/youngsoft/MyLinearLayout/releases/tag/1.3.7)中修复解决。UILabel出现字迹模糊的原因并不是MyLayout本身的问题，而是系统的问题。原因就是当UILabel对象在布局时只要其frame中的origin部分的值是小数，且小到无法对应到相应的物理像素点时就会出现字迹模糊的情况。

举例来说：在一个retina屏幕的设备中，一个设备逻辑点对应2个物理像素。因此0.5个设备逻辑点对应的就是1个物理像素。这也就要求每个视图的frame的值的所有部分都应该是0.5的倍数。而当某个frame值中的某个部分比如origin.y被设置为.13或者.7时那么这个小数值将可能无法正确的映射到真实的物理像素的位置。从而导致在显示时出现模糊的情况。一个解决的方法是我们将UILabel的frame值都统一转化为整数，这可以通过`CGRectIntegral`来将CGRect转化为最接近的整数。另外一个就是借助`MyDimeScale`类中的`roundRect，roundNumber, roundSize, roundPoint`这几个方法来将小数设备点转化为可表示为物理像素的最小设备逻辑点值。在新版本中采用的是后者的解决方法，目的是为了和计算出的frame更加接近。
