### ISSUE TITLE
MyBaseLayout设置bottomBorderline 线太细导致的闪烁问题

### ISSUE THREAD

**Issue by bicyclering** [youngsoft/MyLinearLayout#38]
![2017-05-20 14_15_00](https://cloud.githubusercontent.com/assets/22312518/26611506/537fd1b4-45e1-11e7-8f30-329d6764510a.gif)

layout.bottomBorderline.thick = 1.f / scale 
@youngsoft  大哥的解答:
因为是这样的。如果你设置0.5的话。我这边会按0.5/2的位置来开始展示。但是因为高清屏的位置必须是0.5的倍数，所以导致转化为像素时就有可能无法正确显示。
比如我的底部的高度是5。你如果设置为了0.5的话那么就是从 4.75 - 5.25 这个区域来绘制边界线。
这样因为4.75这个位置是没法有物理像素的位置对应的。所以就抖了

**Comment by youngsoft** [comment]
您好！ 这个问题已经在新发布的[1.3.7](https://github.com/youngsoft/MyLinearLayout/releases/tag/1.3.7)版本中进行了修复。原因就是当布局的边界线对象`MyBorderline`的粗细属性`thick`值小于1时且这个值小到无法用最小一个物理像素来绘制时将会产生闪烁和抖动的现象。因此新版本里面将`thick`的定义改变为了物理像素为单位，最小值为1。如果您设置的值小于1则系统会默认置为1。同时通过对`thick`属性的概念定义为像素也解决了不同物理分辨率下的粗细不一致的问题，您只要设置同样的值就在不同分辨率的设备下显示的线的粗细都是一致的了。
