### ISSUE TITLE
多层嵌套带圆角的view，顶部和底部会被截

### ISSUE THREAD

**Issue by PatShen** [youngsoft/MyLinearLayout#39]
我用了一个UILabel放在了一个多层嵌套的layout上，层级结构大致如下：
|- UITableViewCell.contentView
  |- layoutRoot (MyRelativeLayout)
    |- layoutAccessory (MyLinearLayout，垂直居中)
      |- layoutAccessoryBottom (MyLinearLayout，水平靠右)
        |- lblBadge

label 的属性设置大致如下：
lblBadge.layer.masksToBounds = YES;
lblBadge.layer.cornerRadius = 8.0f;
lblBadge.heightSize.equalTo(lblBadge.heightSize).add(4.0f).lBound(@16,0,1);
lbl.widthSize.equalTo(lbl.widthSize).add(8.0f).lBound(@16,0,1).uBound(_layoutAccessory.widthSize,0,1);

在这一层时，看起来会被截，如下图（放大后）
<img width="372" alt="attach1" src="https://cloud.githubusercontent.com/assets/3346944/26752185/cbfec5f8-487c-11e7-89b5-6b38ea52853e.png">

此时 label 的实际宽高都是正确的，同时使用调试视图看，这个view在最顶层，而且没有其他view盖在上面，如下图（放大后）

<img width="294" alt="attach2" src="https://cloud.githubusercontent.com/assets/3346944/26752197/e98edd92-487c-11e7-938d-1f6f46b296ce.png">

如果将这个视图放到 layoutRoot 中，就不会出现这种现象....

我用的是1.3.8版本

**Comment by PatShen** [comment]
对了，我用的是1.3.8版本

**Comment by youngsoft** [comment]
您好！ @PatShen   从您的反馈的问题来看，这个是否是你的lblBadge的宽度和高度要大于16所导致的。不知道您从布局视图中查看的结果是否是16x16。您可以将您布局的代码发到我的邮箱中来，我这边帮你看看原因，另外您也可以加我QQ：156355113 我们可以在线交流您提出的问题。

**Comment by youngsoft** [comment]
您好。这个问题已经在1.3.9中修复。原因是当设置视图的frame的pt值时如果pt值无法转化为有效的设备的物理像素时将会出现：**文字模糊发虚、线发虚、以及文字无法多行显示、以及当使用layer的cornerRadius时无法绘制出正确的圆形的问题**。因此解决的方案是在布局完成后设置frame时会将pt值四舍五入转化为最小的可显示的物理像素值。
