### ISSUE TITLE
在1.3.8版本中.对scrollview与view的关联滚动中出现了问题.

### ISSUE THREAD

**Issue by kchtin** [youngsoft/MyLinearLayout#40]
情况:将view和scrollview添加到一个相对布局中,其中view在scrollview的左侧.
需求:scrollview往右边滚动的时候,需要将view跟着往右边移动,设置为view.myLeft = -(scrollView.contentOffset.x);当scrollview往左边滚动的时候,view不动view.myLeft = 0;
问题:当scrollview往右边滚动的时候,操作了view.myLeft = -(scrollView.contentOffset.x)之后,发现scrollview的contentoffset被重置为0了.

**Comment by youngsoft** [comment]
这个问题已经在1.3.9版本中进行修复。原因是当UIScrollView的contentOffset值为负数时，如果修改视图的frame值将会把contentOffset的值重置为0.这个是一个系统的特性，因此解决的方案是不修改frame而是修改bounds和center两个属性。
