### ISSUE TITLE
浮动布局里面的子视图的myTop和myLeading之类的不起作用

### ISSUE THREAD

**Issue by bicyclering** [youngsoft/MyLinearLayout#41]
案例:
 
![image](https://cloud.githubusercontent.com/assets/22312518/26814350/82daca88-4ab7-11e7-9500-bb296dc21d83.png)

效果:
![image](https://cloud.githubusercontent.com/assets/22312518/26814356/9ae7d472-4ab7-11e7-8193-e95ef9855246.png)
红色区域没有自动填充

**Comment by youngsoft** [comment]
这个问题已经在v1.3.9版本中修复。原因是当左右两边的子视图尺寸有重合并且高度或者宽度相等时没有将两边的占用区域进行合并，从而影响了新加入的子视图的尺寸设置。
