### ISSUE TITLE
MyFloatLayout weight = 1.f ,视图宽度没有布满

### ISSUE THREAD

**Issue by bicyclering** [youngsoft/MyLinearLayout#42]
![image](https://user-images.githubusercontent.com/22312518/27209859-f82a632c-5280-11e7-9d20-6ba7efe219c3.png)

MyFloatLayout *layout = [MyFloatLayout floatLayoutWithOrientation:MyOrientation_Vert];
    layout.myWidth = self.width;
    layout.subviewSpace = 5.f;
    layout.myHeight = self.height;
    layout.padding = UIEdgeInsetsMake(10.f, 0.f, 0.f, 0.f);
    [self.contentView addSubview:layout];
    self.layout = layout;
    
    UIImageView *mobileImageView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"shop_detail_mobile"] highlightedImage:[UIImage imageNamed:@"shop_detail_mobile"]];
    [layout addSubview:mobileImageView];
    mobileImageView.myWidth = 30.f;
    mobileImageView.myHeight = 30.f;
    mobileImageView.myTop = 8.f;
    mobileImageView.myRight = 10.f;
    mobileImageView.reverseFloat = YES;
    
    UILabel *nameLabel = [UILabel new];
    nameLabel.textColor = [UIColor blackColor];
    nameLabel.font = kSystemFont12;
    [layout addSubview:nameLabel];
    nameLabel.myHeight = 20.f;
    nameLabel.weight = 1.f;
    nameLabel.myLeft = 10.f;
    self.nameLabel = nameLabel;
    
    UILabel *addressLabel = [UILabel new];
    addressLabel.textColor = [UIColor grayColor];
    addressLabel.font = kSystemFont10;
    [layout addSubview:addressLabel];
    addressLabel.myHeight = 20.f;
    addressLabel.weight = 1.f;
    addressLabel.myLeft = 10.f;
    self.addressLabel = addressLabel;
    

    HMSegmentedControl *segmentedControl = [[HMSegmentedControl alloc] initWithSectionTitles:@[@"门店药师",@"门店介绍",@"门店动态"]];
    segmentedControl.selectionStyle = HMSegmentedControlSelectionStyleFullWidthStripe;
    segmentedControl.selectionIndicatorLocation = HMSegmentedControlSelectionIndicatorLocationDown;
    segmentedControl.verticalDividerEnabled = YES;
    segmentedControl.verticalDividerColor = kBgColor;
    segmentedControl.verticalDividerWidth = CGFloatFromPixel(1.f);
    segmentedControl.selectionIndicatorHeight = 1.f;
    segmentedControl.selectionIndicatorColor = [UIColor colorWithHexString:@"#B82D2D"];
    segmentedControl.selectedTitleTextAttributes = @{NSForegroundColorAttributeName : [UIColor blackColor],NSFontAttributeName:kSystemFont12};
    segmentedControl.titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor grayColor],NSFontAttributeName:kSystemFont12};
    [layout addSubview:segmentedControl];
    self.segmentedControl = segmentedControl;
    segmentedControl.clearFloat = YES;
    segmentedControl.weight = 1.f;
    segmentedControl.myHeight = 40.f;

**Comment by youngsoft** [comment]
新版本V1.4.0已经修复这个问题。
