### ISSUE TITLE
请问有首行文本的基线属性吗?

### ISSUE THREAD

**Issue by markalex25** [youngsoft/MyLinearLayout#43]
请问有首行文本的基线属性吗?
例如文本首行前加上圆点.
leftPointIv.centerYPos.equalTo(textLbl.基线);

**Comment by youngsoft** [comment]
@markalex25  好问题，基于基线的逻辑目前是暂时不支持的。不过会在下一个版本里面添加对基线的支持。

**Comment by youngsoft** [comment]
您好！最新发布的V1.5.0版本已经提供了基线对齐的能力了。。

**Comment by markalex25** [comment]
抱歉,我发现baselinePos不支持多行的Label.
以Demo的RLTest1ViewController为例 288行
walkLabel2.text = @"Weight\n123";
walkLabel2.numberOfLines = 2;

**Comment by bicyclering** [comment]
支持多行的,但是你要设置要这个wealkLabel2的尺寸的约束
例如这样：
   walkLabel2.heightSize.equalTo(@50);
    walkLabel2.widthSize.equalTo(@100);

**Comment by youngsoft** [comment]
目前只是支持单行文本的基线对齐，我不知道这种多行的基线对齐是否有对应的需求，如果是多行的话是否是只是以第一行的文本作为基线对齐的标准。@markalex25

**Comment by markalex25** [comment]
![image](https://user-images.githubusercontent.com/1716660/31873930-02dd922e-b78c-11e7-901e-35dcf1d2e11b.png)
@youngsoft 希望Html5的样式相近.
参考:http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html?utm_source=tuicool
align-items:baseline

**Comment by youngsoft** [comment]
* 另外一个就是线性布局MyLinearLayout。你可以为线性布局中的`baselineBaseView`属性来设置基线视图的标准视图。然后你可以通过布局视图的gravity属性以及子视图的myAlignment属性来设置基线对齐的方式，就和你上面引用的文档类似，具体的例子可以参考LLTest2ViewController中的DEMO有具体的介绍。

**Comment by markalex25** [comment]
好的 谢谢
