### ISSUE TITLE
MyBorderline 设置headIndent有效，但是设置tailIndent无效，是怎么回事啊。

### ISSUE THREAD

**Issue by shaozhe-chen** [youngsoft/MyLinearLayout#44]
MyBorderline *rightLayoutBld = [[MyBorderline alloc] initWithColor:COLOR_WITH_HEX(@"222222")];
    rightLayoutBld.tailIndent = 15;
    rightLayoutBld.headIndent = 15;
    rightLayoutBld.dash = 0;
    rightLayoutBld.thick = 1;
    self.rootLayout.bottomBorderline = rightLayoutBld;

**Comment by youngsoft** [comment]
从这部分代码来看应该是没有问题的。因为你这里是底部的边线，因此headIndent和tailIndent是指左右的缩进。不知道你是否还把rightLayoutBld中的属性进行其他的设置。。具体问题你可以加我QQ:156355113和我具体交流。
