### ISSUE TITLE
例子中的那个tableview-动态高度在有些模拟器上跑很卡，比如6Plus 8.1系统。

### ISSUE THREAD

**Issue by mahailin** [youngsoft/MyLinearLayout#48]
例子中的那个tableview-动态高度在有些模拟器上跑很卡，比如6Plus 8.1系统。

**Comment by youngsoft** [comment]
好问题。是这样的我这边模拟器测试iOS8系统也会比较卡尤其是那个动态高度tableview的例子。原因并不是这个库，而是模拟器的问题，真机并不会出现这种问题。 主要原因是字体导致的模拟器非常的慢。因为如果字体使用不正确的话在计算sizeToFit方法时将会非常的慢。。。
