### ISSUE TITLE
是否可以异步调用 estimateLayoutRect 计算高度

### ISSUE THREAD

**Issue by Homin818** [youngsoft/MyLinearLayout#49]
estimateLayoutRect 是否可以放在后台使用

**Comment by youngsoft** [comment]
如果您的动态高度评估包括了UILabel的动态高度计算的话，就一般不能在其他线程里面处理的，但是这个我也没有具体的试过啊。你可以试试看是否可以通过异步线程去进行高度评估。如果你是想用UITableView+FDTemplateLayoutCell结合的话，是有同学使用它和MyLayout高度评估结合的。

如果你是用在我的DEMO例子里面的话，那么目前DEMO的解决方案是不支持后台计算高度的评估的。不过你可以去尝试一下。。。然后我们再可以后续交流。
