### ISSUE TITLE
楼主写的很不错, 只是...

### ISSUE THREAD

**Issue by TianXiaoBei** [youngsoft/MyLinearLayout#50]
我只说下初次接触这个框架的感觉
不容易理解
不像masonry参考自动布局的方式 就能猜出代码怎么写.
调用比较麻烦
虽然底层实现用frame, 但是调用方式楼主能不能改进一下,  搞简单一些, 比如简单的设置下左间距,右间距,宽度大于等于多少,小于等于多少, 内容不要挤我等等吧
大家熟知的东西,在框架中基本没看到
先从API接口命名开始吧,我个人建议,得在优化优化

**Comment by youngsoft** [comment]
非常好的建议，OC版本在开始推出的时候，有很多命名包括使用方法都不是很规范。后来也接收了很多的建议，以及做了很多的改动。一个原因是有了一定的用户使用基础，无法像swift那样新版本可以把老版本的东西推翻重来。目的还是为了兼容性考虑。不过在最近的几个版本里面都已经将很多方法名进行了改进和优化了。

至于你说的左间距和右间距宽度和高度的设置都分别提供了比如myLeft, myRight, myWidth, myHeight等相应的属性来进行设置。

另外使用风格上还是遵循苹果的标准采用属性设置为主，而不是masonry所提供的block和链式编程方式。（个人不是很推崇所谓的block以及链式编程）。同时为了兼容那些masonry的爱好者，MyLayout也提供了一个myMaker之类的语法糖设置方法，这个和masonry是非常相似的。

最后要说的是后续的swift版本TangramKit中对很多属性和方法名的使用进行很多的优化和统一，而且使用起来也非常的简单和清楚。


在后面的OC版本我将会继续对方法进行优化和简化。。多谢你的提议。。

**Comment by 1046964106** [comment]
这个和android的布局很像嘛!
