### ISSUE TITLE
要如何知道LinearLayout的高度呢?

### ISSUE THREAD

**Issue by lmw4051** [youngsoft/MyLinearLayout#52]
感謝您做了很好用的工具，但我想知道，要如何得知自動計算之後的高度要怎麼取得呢?

**Comment by youngsoft** [comment]
在一般情况下我们都不需要去获取那些设置为wrapContentHeight的布局视图的高度。如果你要获取自动计算后的高度你可以有三种方法：

1.对布局视图调用layoutIfNeed，然后就可以通过布局视图的frame值读取高度。这种方法是要获取高度时必须要先布局完成。

2.通过对布局视图调用sizeThatFits方法来对布局视图的高度进行评估，然后通过这个方法的返回来获得布局视图的高度。这种方法时布局还没有完成布局就想得到高度。

3.实现布局视图的endLayoutBlock这个方法。这个方法会在布局完成一次后调用，你可以在这个block方法内部读取到布局视图的frame值来获取布局视图的高度。
