### ISSUE TITLE
建议：增加Xcode 8的兼容

### ISSUE THREAD

**Issue by zkhCreator** [youngsoft/MyLinearLayout#54]
建议：增加@avaliabe，从而完成对Xcode 8 的兼容。否则拿 Xcode 8 编译出来都是一堆warning。

**Comment by faimin** [comment]
你想说的是Xcode9吧，@avaliabe是Xcode9才支持的特性，目前还有人在用Xcode8，这样人家一编译就会报错的。

**Comment by zkhCreator** [comment]
给大佬低头。

**Comment by youngsoft** [comment]
您好！已经在1.5.0版本中解决了您的问题。
