### ISSUE TITLE
要如何針對iPhoneX的UI做調整呢?

### ISSUE THREAD

**Issue by lmw4051** [youngsoft/MyLinearLayout#55]
想請問如果我沒使用AutoLayout，只用MyLinearLayout要如何針對iPhoneX來調整跑版的UI呢?

**Comment by youngsoft** [comment]
您好！ 在最新的**1.5.0**版本中对iOS11以及iPhoneX的适配都做了很好的优化处理：

1.对于布局视图增加了两个属性：`insetsPaddingFromSafeArea` 和`insetLandscapeFringePadding`分别用来处理安全区的问题，也就是默认情况下你可以将安全区的尺寸叠加到布局视图的padding里面去。具体您可以参考这两个属性的注释，以及在DEMO中搜索关键字来进行查看如何使用这两个属性。

2.添加了一个新的特殊值：`MyLayoutPos.safeAreaMargin` 这个值是用来适配所有iOS版本以及所有iPhone设备的。具体您可以在DEMO搜索关键字来进行了解。
