### ISSUE TITLE
这个和android的布局很像嘛!

### ISSUE THREAD

**Issue by 1046964106** [youngsoft/MyLinearLayout#56]

**Comment by youngsoft** [comment]
看来你也熟悉android的东西。MyLayout是集成了android的4大布局，以及新推出的百分布局等等。但是功能却更加强大于android的布局。另外还集成了HTML中的浮动、flexbox等。以及自有的路径布局，栅格布局，还有集成了iOS的autolayout和sizeclass以及UIStackView等等众多市面上流行的布局框架。

**Comment by 1046964106** [comment]
给大佬点烟.... ,这个框架 小弟我收下了额!

**Comment by wy19901227** [comment]
Hidden 后会重新布局吗

**Comment by youngsoft** [comment]
hidden以后会激发子视图的自动重新布局，而且还会自动影响布局的界面，也就是子视图隐藏后是可以设置为是否占位显示的，具体您可以用myVisibility属性来设置，这个属性是对hidden属性的一个扩展。

**Comment by luffykou** [comment]
@youngsoft 
谁说这个比Android布局强大了？[ConstraintLayout](https://developer.android.com/reference/android/support/constraint/ConstraintLayout.html)笑而不语

**Comment by youngsoft** [comment]
ConstraintLayout 以及PercentXXXXLayout这些这些东西我都有了解过也对比过，ConstraintLayout 中 PercentXXXXLayout有的MyLayout的都有，但是后者有的前两者就不一定有。

**Comment by bacy** [comment]
能搞个LayoutInflater出来么，让ios也能用上xml布局~~
