### ISSUE TITLE
对于 MyFlowLayout 的使用困惑

### ISSUE THREAD

**Issue by zkhCreator** [youngsoft/MyLinearLayout#57]
我看了下现有的 FLLTest2ViewController 的处理，只是设置了对应的 padding 和 weight ，width 和 height 均为 1。然后我也尝试这么设置了。但是结果是，所有的标签都是左对齐，理论上按照现有的情况进行设置的话，应该是自动排布。还是说我用错了类？应该使用 FloatView？
P.S. 外部的父 view 是 scrollView
![image](https://user-images.githubusercontent.com/12930558/31751885-a0c80a06-b44d-11e7-9715-4f6759d05209.png)

```
- (void)setupView {
    _layout.wrapContentHeight = YES;
    _layout.subviewSpace = 16.f;
    _layout.padding = UIEdgeInsetsMake(24.f, 24.f, 24.f, 24.f);
    _layout.weight = 1;
    _layout.myMargin = 0;
    
    [self addSubview:_layout];
}

- (UIButton *)createButtonWithModel:(BBSPostTagModel *)model {
    UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
    button.tag = model.tagID;
    [button setTitle:model.title forState:UIControlStateNormal];
    button.titleLabel.font = [UIFont systemFontOfSize:15.f];
    button.layer.cornerRadius = 19.f;
    [button setTitleColor:RGBColorHex(0x4B4F56) forState:UIControlStateNormal];
    [button setTitleColor:[UIColor whiteColor] forState:UIControlStateSelected];
    [button setBackgroundColor:RGBColorHex(0xF6F7F9)];
    button.widthSize.equalTo(button.widthSize).add(32.f);
    button.myHeight = 37.f;
    [button sizeToFit];
    
    [button addTarget:self action:@selector(clickButton:) forControlEvents:UIControlEventTouchUpInside];
    
    return button;
}
```

**Comment by zkhCreator** [comment]
结果是 flowLayout 创建的时候的问题。顺便问题问题，上面出现的方式我是使用 MyOrientation_Horz  进行创建的，但是理论上来说应该是从左到右进行布局。但是当我使用 MyOrientation_Vert 进行布局的时候出现的才是从左到右，满了之后就换行。感觉语义上面存在问题。

**Comment by MineJ** [comment]
MyOrientation_Horz 是从上到下 
MyOrientation_Vert 是从左到右

**Comment by zkhCreator** [comment]
```

/**
 *布局视图方向的枚举类型定义。用来指定布局内子视图的整体排列布局方向。
 */
typedef enum : unsigned char {
    MyOrientation_Vert = 0,  /**垂直方向，布局视图内所有子视图整体从上到下排列布局*/
    MyOrientation_Horz = 1,  /**水平方向，布局视图内所有子视图整体从左到右排列布局*/
    
    
    //兼容老版本而定义，请使用新的定义值。
    MyLayoutViewOrientation_Vert MYMETHODDEPRECATED("use MyOrientation_Vert to instead") = MyOrientation_Vert,
    MyLayoutViewOrientation_Horz MYMETHODDEPRECATED("use MyOrientation_Horz to instead") = MyOrientation_Horz,
    
} MyOrientation;

```
@MineJ

**Comment by youngsoft** [comment]
首先第一个问题：
1.流式布局有内容约束有数量约束，我估计你是建立的数量约束布局吧。你应该如下创建布局：
   _layout = [MyFlowLayout flowLayoutWithOrientation: MyOrientation_Vert arrangedCount:0];
并把autoArrange属性设置为YES。这样才能会根据内容自动排列。确保你的布局代码的建立是正确的。因为没有看到你的布局代码的创建，这也是我猜测的。

2.第二个问题就是所谓的方向，这里的方向是最终的方向，不是每一行或者每一列的方向，比如MyOrientation_Vert 是表示每行从左到右，但是最终整体是从上到下排列的。

3.你这里设置的    _layout.weight = 1;其实是没有作用的。

**Comment by zkhCreator** [comment]
@youngsoft 感谢，因为默认理解的时候，item 的方向是从左到右的。所以默认是使用了 MyOrientation_Horz 作为创建。其余的都是一致的。建议在 MyOrientation 上面增加对于 FlowLayout 的单独处理的注释。
