### ISSUE TITLE
像淘宝的评价详情那样，加载多张网络图片

### ISSUE THREAD

**Issue by billlk123** [youngsoft/MyLinearLayout#58]
你好，我现在要实现一个淘宝的评价详情的类似界面。
要竖直加载多张评价的图片，图片和屏幕等宽，高度根据图片本身的尺寸确定。如果要使用这个框架，该怎么实现。而且我这个是要做为表视图的头视图来使用的

**Comment by youngsoft** [comment]
我看了一下淘宝的评价详情，没有你说的这个界面。不过你是不是想实现如下的需求：

用tableview的tableviewheaderview来实现多张图片从上到依次排列的场景。然后每张图片的宽度和屏幕宽度等宽，而高度则是根据屏幕的宽度以及自身的高度来实现自动缩放以便达到不变形的效果。

那这个解决方案就是你可以将tableviewheaderview设置为一个垂直线性布局MyLinearLayout。

```
MyLinearLayout *header = [[MyLinearLayout  alloc] initWithFrame:CGRectMake(0,0,tableview的frame.size.width, 0) orientation:MyLayoutViewOrientation_Vert];
header.gravity = MyGravity_Horz_Fill;  //设置里面的子视图宽度和自己保持一致。

//..这里添加UIImageView子视图。然后设置UIImageView子视图的wrapContentHeight = YES; 不需要指定宽度。

//然后调用
[header layoutIfNeed];

tableView.tableHeaderView = header;

```
具体你可以参考AllTest1ViewController和TLTest2ViewController中关于tableHeaderView的例子和图片高度自适应的例子。

你还可以加我的qq来和我交流：156355113
