### ISSUE TITLE
问下，使用了这套框架后，对动画支持的怎么样

### ISSUE THREAD

**Issue by 429329513wanting** [youngsoft/MyLinearLayout#6]

**Comment by youngsoft** [comment]
您好，这套布局对动画是完全支持的，请看我的DEMO15中有使用动画的场景，只需要设置beginLayoutBlock和endLayoutBlock中设置动画的开始和结束即可，而且布局里面的属性以及视图的扩展属性都是支持动画效果的。

**Comment by 429329513wanting** [comment]
好的。十分感谢
