### ISSUE TITLE
MyRelativeLayout布局错误

### ISSUE THREAD

**Issue by applebest** [youngsoft/MyLinearLayout#63]
控制器的VIew为普通View在ViewDidLoad中创建 MyRelativeLayout 并加入到self.view中，通过生产的MyRelativeLayout对象做布局会崩溃在下面的函数中  suv = nil    sbvsc = nil 

myCalcSubViewTopBottom:(UIView*)sbv sbvsc:(UIView*)sbvsc lsc:(MyRelativeLayout*)lsc sbvmyFrame:(MyFrame*)sbvmyFrame selfSize:(CGSize)selfSize

**Comment by applebest** [comment]
![1517196773016](https://user-images.githubusercontent.com/16376401/35492506-2d9ec038-04e8-11e8-83b2-e9f2e730ec55.jpg)

将注释打开就会崩溃

**Comment by applebest** [comment]
![1517197752554](https://user-images.githubusercontent.com/16376401/35492899-7a912c26-04ea-11e8-96f6-84380ab75165.jpg)

此布局代码会产生布局错乱 ，之前的两个label会不显示

**Comment by youngsoft** [comment]
您好。我这边根据你的代码写的DEMO都是正常的，并没有出现你所说的崩溃问题。不知道你所使用的库的版本是否是最新版本还是哪个版本？ 。如果您升级到最新版本还是出现同样问题，你可以通过QQ联系我：156355113。

另外如果您贴代码时最好贴源代码而非截图，这样我就更好的对你的代码进行分析和处理。谢谢
