### ISSUE TITLE
您好，看了您框架的相关信息，准备使用。问个问题

### ISSUE THREAD

**Issue by puyang0521** [youngsoft/MyLinearLayout#67]
这套框架，如果用于一套代码同时适配iPhone和iPad，不知是否方便，有哪些需要注意的问题吗

**Comment by youngsoft** [comment]
您好。欢迎使用，其实需要注意的点都是github上的文档，以及在DEMO里面有非常详细的说明了。建议你在用之前先阅读一下DEMO里面的代码，里面会告诉你很多的，当然你可以加入178573773这个QQ讨论群。
