### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by jyounus** [youngsoft/MyLinearLayout#7]
Hey,

Any chance for an english translation of this please?

Thanks

**Comment by youngsoft** [comment]
thanks for you suggestion, i will be able to translation to english description.

**Comment by jyounus** [comment]
Thanks :)

**Comment by youngsoft** [comment]
Hi:)  sorry for let you waiting...it takes me too long time to release the i18n version 1.1.9, as my English is not good enough, i just translated part of it, and in the future i will continue to improve it, if you have any advises and suggestions please feel free to let me know. Thanks for your attention!
