### ISSUE TITLE
MyPathSpace中initWithType:value:与CoreBluetooth中的CBDescriptor存在重名方法

### ISSUE THREAD

**Issue by ShenYj** [youngsoft/MyLinearLayout#70]
非常感谢你分享的这么优秀的布局工具, 我是做蓝牙开发的, 集成MyLayout后编译报错, 而在自己的本写测试Demo时未曾遇到, 最终确认是与CoreBluetooth中的CBDescriptor存在重名方法

**Comment by youngsoft** [comment]
您好，问题已经在最新发布的1.5.2中修复，请及时更新库，出现这个问题的原因是：

"In one scenario, if the factory method that creates the object has return type "id" then the compiler will check the method signature in all the classes. If compiler find the same method signature in more than one class then it will raise the issue. So replace the return type "id" with "specific class name"."
