### ISSUE TITLE
Flowlayout?

### ISSUE THREAD

**Issue by neobie** [youngsoft/MyLinearLayout#73]
Hi, 

Is there something similar to "https://github.com/nex3z/FlowLayout" (from Android) ?

MyFlowlayout isn't bad, but I need to set the items per row. I wish it can behave like collectionview

**Comment by youngsoft** [comment]
Hi,

Yes! There is a Layout named [MyFlowLayout](https://github.com/youngsoft/MyLinearLayout/blob/master/MyLayout/Lib/MyFlowLayout.h) in `MyLayout`. Almost  all functions in "https://github.com/nex3z/FlowLayout"  can  supported by `MyFlowLayout`, and `MyFlowLayout` is a subset of  "flex-box".   You can see the demo  from  [FLLTest1ViewController1](https://github.com/youngsoft/MyLinearLayout/blob/master/MyLayoutDemo/FLLTest1ViewController.h) to [FLLTest7ViewController](https://github.com/youngsoft/MyLinearLayout/blob/master/MyLayoutDemo/FLLTest7ViewController.h)  to understand  how to use 'MyFlowLayout'.
