### ISSUE TITLE
Carthage方式，Could not build module 'MyLayout'

### ISSUE THREAD

**Issue by XinQiXiao** [youngsoft/MyLinearLayout#74]
按readme文档中carthage方式导入的，carthage导入成功后，在m文件中，“#import <MyLayout/MyLayout.h>”引入文件，提示Could not build module 'MyLayout'。

**Comment by youngsoft** [comment]
抱歉，因为工作的原因没有看到您的问题，您的问题已经修复了，请再试试！

**Comment by XinQiXiao** [comment]
感谢更新。经测试，在项目中,carthage update 最新tag版本，可以正常使用，非常棒。
