### ISSUE TITLE
关于layoutAnimationWithDuration播放动画后结束的问题

### ISSUE THREAD

**Issue by tq04t46** [youngsoft/MyLinearLayout#75]
您好，咨询一个问题就是我想在layoutAnimationWithDuration动画播放完成后去做另外的动作，目前好像没看到框架有提供类似的方法，只能自己手动在beginLayoutBlock里用setAnimationDelegate和setAnimationDidStopSelector来实现，想知道框架会不会提供一个类似的block去完成这个操作？

**Comment by youngsoft** [comment]
你好，其实动画这块是开放的，和普通视图执行动画一样。如果你不想用系统自带的动画API。你可以实现如下：

```
 [UIView animateWithDuration:0.5  animations:^{
        
       [layout layoutIfNeed];   

}  completion:^(BOOL finished){
     
     //这里做你自己的事情。   

}];

```
