### ISSUE TITLE
某些场景下会影响响应链的响应顺序

### ISSUE THREAD

**Issue by BarneyEY** [youngsoft/MyLinearLayout#76]
场景：图层关系：UITableViewCell -> MyRelativeLayout -> UIButton

点击btn时，期望可以拦截到当前touch.view为UIButton，相应的做后续逻辑；
看到的结果，通过手势与hit拦截到的当前touch.view为MyRelativeLayout；同时触发didSelectRowAtIndexPath，毁三观

不知道是不是MyRelativeLayout内部做了特殊处理，期待您的回复

**Comment by youngsoft** [comment]
您好。我这边经过测试，在相对布局里面添加UIButton后，然后UIButton是可以处理和捕获事件的，并且并没有被MyRelativeLayout拦截，我估计这时候你的UIButton虽然能够显示但是尺寸size是0的原因吧，导致事件直接传递给TableViewCell了。 您可以调试查看一下视图树，看看你此时的UIButton的frame值是不是为0。

**Comment by BarneyEY** [comment]
嗯，层级是 UITableViewCell - > layoutA ->layoutB -> btn;
layoutB的约束设置错了，导致视图frame为0
