### ISSUE TITLE
RelativeLayout wrapContentHeight 似乎有問題

### ISSUE THREAD

**Issue by Elvis5566** [youngsoft/MyLinearLayout#78]
歐陽大哥你好，

我正在嘗試把RelativeLayout 放進Vertical LinearLayout裡
RelativeLayout的高度是由wrapContent決定
目前測試高度計算似乎有問題
在這個[測試app](https://github.com/Elvis5566/TryRelativeLayoutInLinearLayout)
如同ViewController.m 的注解
comment out line 51, uncomment line 52, yellowRelativeLayout 高度應該要是110,
但render完yellowRelativeLayout的高度卻是50 (應該是top offset 10 + bottomOffset 40)
完全看不到blueView

請大哥解惑 謝謝

**Comment by youngsoft** [comment]
您好，
抱歉才看到您的问题，原因是这样的：因为你的yellowRelativeLayout的高度设置为wrapContentHeight = YES表示高度由子视图包裹决定，但是yellowRelativeLayout的子视图的约束：
```
    blueView.topPos.equalTo(yellowRelativeLayout.topPos).offset(10);
    blueView.bottomPos.equalTo(yellowRelativeLayout.bottomPos).offset(40);
```
这两句代码的意思是blueView的上边依赖于父视图的上边偏移10，而下边依赖于父视图的下边偏移40，也就是说子视图blueView的高度依赖于父视图yellowRelativeLayout的高度，这样就和父视图yellowRelativeLayout的高度又依赖于子视图的高度是矛盾了，所以才会出现您的疑问。

在MyLayout的相对布局中的子视图，如果同时设置了top和bottom是一个具体的数字或者都是依赖于父视图时就表明子视图的高度是依赖于父视图的，就如同时设置left和right一样，这一点是和苹果的autolayout是有差异的。因此要解决您的问题您可以这样设置：

```
 UIView *blueView = [UIView new];
    blueView.backgroundColor = UIColor.blueColor;
    blueView.topPos.equalTo(yellowRelativeLayout.topPos).offset(10);
    blueView.leftPos.equalTo(yellowRelativeLayout.leftPos).offset(20);
    blueView.rightPos.equalTo(yellowRelativeLayout.rightPos).offset(30);
 //   blueView.bottomPos.equalTo(yellowRelativeLayout.bottomPos).offset(40); //注释他表明blueView不会依赖于父视图的高度了。
   blueView.myHeight = 200; //明确设置子视图的高度。
   yellowRelativeLayout.bottomPadding = 40;  //父视图底部缩进40.
```

**Comment by Elvis5566** [comment]
原來如此，我的確是用autolayout的思維
非常感謝你的回答!
