### ISSUE TITLE
mylayout对xcode有要求？

### ISSUE THREAD

**Issue by tanjieaa** [youngsoft/MyLinearLayout#80]
因为电脑也装了xcode8.3，用xcode8.3打开会报错在safeAreaInsetsDidChange

**Comment by youngsoft** [comment]
不知道您的最新版本的库是多少？我记得在我的safeAreaInsetsDidChange函数的实现中增加了一些宏定义处理：
```
#if (__IPHONE_OS_VERSION_MAX_ALLOWED >= 110000) || (__TV_OS_VERSION_MAX_ALLOWED >= 110000)

    [super safeAreaInsetsDidChange];
#endif
```

按理来说应该不会报这个错误的。因为xcode8.3中的__IPHONE_OS_VERSION_MAX_ALLOWED应该不大于110000的。

**Comment by tanjieaa** [comment]
我是早上pod下来的

**Comment by tanjieaa** [comment]
我是早上pod下来的，在MyBaseLayout里，没有这个判断啊，就是报错在这里的

-(void)safeAreaInsetsDidChange
{
    [super safeAreaInsetsDidChange];
    
    
    if (self.superview != nil && ![self.superview isKindOfClass:[MyBaseLayout class]] &&
        (self.leadingPosInner.isSafeAreaPos ||
         self.trailingPosInner.isSafeAreaPos ||
         self.topPosInner.isSafeAreaPos ||
         self.bottomPosInner.isSafeAreaPos)
        )
    {
        if (!_isMyLayouting)
        {
            _isMyLayouting = YES;
            [self myUpdateLayoutRectInNoLayoutSuperview:self.superview];
            _isMyLayouting = NO;
        }
    }
}

**Comment by youngsoft** [comment]
那是你的本地pod库的缓存版本太低了。目前最新的已经是1.6.0了，你执行一下pod update或者更新一下 pod的本地缓存即可。

**Comment by tanjieaa** [comment]
是的，更新就没问题了，谢谢
