### ISSUE TITLE
在Today Extension中无法使用，应为Today Extension中没有UIApplication对象

### ISSUE THREAD

**Issue by tanranran** [youngsoft/MyLinearLayout#81]
如题

**Comment by youngsoft** [comment]
这个和UIApplication对象没有关系吧。

**Comment by tanranran** [comment]
@youngsoft 
MyViewSizeClass  里面的myLayoutTopPadding 方法里面用到了[UIApplication sharedApplication].statusBarFrame

而Today Extension里面是用不了UIApplication sharedApplication的

**Comment by youngsoft** [comment]
好的，知道原因了，我最近正在准备升级一个版本为了支持iPhoneX 系列的新设备以及iOS12和XCODE10。就这两天会出一个新的版本，请稍候。。。

**Comment by tanranran** [comment]
@youngsoft 谢谢大佬，我可能是第一个用MyLinearLayout写Today Extension O(∩_∩)O

**Comment by youngsoft** [comment]
@tanranran 新版本已经可以支持Application Extension的能力了，请更新到1.6.1

**Comment by tanranran** [comment]
@youngsoft 好的，谢谢大佬。

**Comment by tanranran** [comment]
1.6.1已经可以完美使用

**Comment by tanranran** [comment]
@youngsoft 谢谢大佬，1.6.1已经可以完美使用
