### ISSUE TITLE
要如何動態更動View的座標?

### ISSUE THREAD

**Issue by lmw4051** [youngsoft/MyLinearLayout#83]
想請問歐陽大哥，要如何動態更動View的座標呢? 比如按下鍵盤，UITextField被擋到，整個LinearLayout會向上移動。

**Comment by youngsoft** [comment]
LinearLayout就是一个UIView的派生类，它也是一个View，至于要实现你的UITextField被阻挡后让LinearLayout往上移的话，你可以借助一些第三方库比如IQKyeboardManager，或者你可以监控键盘弹出的事件，然后通过调整LinearLayout的topPos或者调整LinearLayout的frame都可以实现。

**Comment by lmw4051** [comment]
感謝歐陽大哥的回覆，我是透過改變bottomMargin 和 改變 frame.origin.y 值而完成這個功能。
