### ISSUE TITLE
endLayoutBlock怎么获取所有子视图的frame

### ISSUE THREAD

**Issue by Whaiyan** [youngsoft/MyLinearLayout#84]
endLayoutBlock怎么获取所有子视图的frame？返回值为空，也没有传入的值

**Comment by youngsoft** [comment]
endLayoutBlock是指定在布局视图一次完成后的一次回调处理，这个只会触发一次。
viewLayoutCompleteBlock 则是子视图布局完成一次后的回调处理，这个也只会触发一次。

一般情况下这两个回调里面都能获取到布局视图或者子视图的frame的。但是在一些复杂的布局约束中比如带有包裹性质的约束中则因为布局计算会来回多次所以有可能这两个回调中的视图的frame不一定正确。

不过一般情况下采用布局约束后不再需要去关注子视图的frame，除非我们要做一些子视图layer层面的设置，比如圆角半径，或者添加子layer。这时候可以用一下的一些方法：
1.导入一些第三方的KVO库来监视frame的变化，或者用我的开源库YSObserver来监控。
2.对布局调用layoutIfNeed来实现布局视图的真实布局，这样就可以算出子视图的frame值了。
3.可以采用sizeToThatFits来对布局进行评估从而得到子视图的评估值estimatedRect，这个值应该和frame比较接近了。

-------然后你的问题中endLayoutBlock获取子视图的frame值你可以尝试一下在block中调用布局视图的subviews来遍历子视图的frame看看。

**Comment by karosLi** [comment]
由于 setViewLayoutCompleteBlock 获取的不是最后的frame，目前我是这样设置部分圆角的

[contentLayout setViewLayoutCompleteBlock:^(MyBaseLayout *layout, UIView *v) {
        CGSize size = [v sizeThatFits:CGSizeMake(v.bounds.size.width, 0)];
        CGRect frame = CGRectMake(0, 0, size.width, size.height);
        
        // 设置左上角右上角u圆角
        UIBezierPath *maskPath = [UIBezierPath bezierPathWithRoundedRect:frame byRoundingCorners:UIRectCornerTopLeft | UIRectCornerTopRight cornerRadii:CGSizeMake(16, 16)];
        CAShapeLayer *maskLayer = [[CAShapeLayer alloc] init];
        maskLayer.frame = frame;
        maskLayer.path = maskPath.CGPath;
        v.layer.mask = maskLayer;
    }];
