### ISSUE TITLE
刷新数据后 scrollView的contentsize不对

### ISSUE THREAD

**Issue by Whaiyan** [youngsoft/MyLinearLayout#85]
`    if(contentLayout!=nil){
        [contentLayout removeAllSubviews];
        contentLayout=nil;
    }
    contentLayout = [MyLinearLayout linearLayoutWithOrientation:MyOrientation_Vert];
    contentLayout.padding = UIEdgeInsetsMake(0, 0, 10, 0); //设置布局内的子视图离自己的边距.
    contentLayout.myHorzMargin = 0;                          //同时指定左右边距为0表示宽度和父视图一样宽
    contentLayout.heightSize.lBound(scrollView.heightSize, 10, 1); //高度虽然是wrapContentHeight的。但是最小的高度不能低于父视图的高度加10.
   
    [scrollView addSubview:contentLayout];`
由于添加的都是单个view 所以是先移除再添加，但是刷新完数据后 scrollView的contentsize就变成了只比界面高10 添加的内容也添加好了 就contentsize有问题

**Comment by youngsoft** [comment]
没有明白你要表达的意思。不过从上面的布局约束来看是表示contentLayout的高度是包裹的(由子视图的高度决定自身的高度)但是最小高度是scrollview视图的高度+10。一般情况下将布局视图加入到scrollView时系统在完成布局后调整scrollView的contentSize。这样contentSize的高度值就等于contentLayout的高度值。如果你愿意你可以加QQ群：178573773  来具体讨论你问题的细节。

**Comment by Whaiyan** [comment]
群满员了啊 


------------------ 原始邮件 ------------------
发件人: "欧阳大哥2013"<notifications@github.com>;
发送时间: 2019年4月16日(星期二) 下午2:17
收件人: "youngsoft/MyLinearLayout"<MyLinearLayout@noreply.github.com>;
抄送: "遥遥浅浅"<1352461828@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youngsoft/MyLinearLayout] 刷新数据后 scrollView的contentsize不对 (#85)




没有明白你要表达的意思。不过从上面的布局约束来看是表示contentLayout的高度是包裹的(由子视图的高度决定自身的高度)但是最小高度是scrollview视图的高度+10。一般情况下将布局视图加入到scrollView时系统在完成布局后调整scrollView的contentSize。这样contentSize的高度值就等于contentLayout的高度值。如果你愿意你可以加QQ群：178573773  来具体讨论你问题的细节。

**Comment by youngsoft** [comment]
不好意思，请再试一次。
