### ISSUE TITLE
你好，怎样可以获取 myFlowLayout  的内容高度？

### ISSUE THREAD

**Issue by pttyy** [youngsoft/MyLinearLayout#87]
#import "CGFlowLayout.h"

@implementation CGFlowLayout

-(CGSize)intrinsicContentSize
{
    CGSize sz = [self sizeThatFits:CGSizeMake(SCREEN_WIDTH, 0)];
    return sz;
}
按照你这样做并不能获取高度，返回的height = 0。通过self.flowLayout.wrapContentHeight 和 self.flowLayout.myHeight 配合 

- [x] 得到的高度也为0，我是用你 myFlowLayout  做流式布局 ，放在一个动态高度的 cell 上,所以需要得到 这一块的内容高度。

[self.flowLayout mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.bottomLine1.mas_bottom).offset(0);
        make.left.equalTo(self.contentView);
        make.width.mas_equalTo(SCREEN_WIDTH);
        //make.height.mas_equalTo(130);
        make.bottom.equalTo(self.contentView);
    }];

1. 

![image](https://user-images.githubusercontent.com/13176599/57443403-8dafcd80-7280-11e9-8985-08c4a5ccce5b.png)
   @@@@

**Comment by youngsoft** [comment]
您的 -(CGSize)intrinsicContentSize 函数在执行时高度返回0？您先检查一下在调用这个函数里面的子视图都已经添加完毕。

另外您不需要设置flowLayout的高度约束。不管是MyLayout约束还是AutoLayout约束。你只需要设置flowLayout.wrapContentHeight = YES即可。

**Comment by pttyy** [comment]
谢谢，已解决，是我这边的原因

**Comment by youngsoft** [comment]
您好，这是一个迟来的更新，目前在最新发布的1.7.0版本中布局视图内部通过重载intrinsicContentSize的方法已经实现了布局视图尺寸自适应和autolayout结合的问题了，处理的例子请参考最新的项目中的DEMO文件：AllTest12ViewController.m。以及MyLayout高度自适应在UITableViewCell中的最新使用形式, 请参考具体的实现代码。
