### ISSUE TITLE
能否支持一下Swift?

### ISSUE THREAD

**Issue by bxcx** [youngsoft/MyLinearLayout#9]
直接OC编进Swift的项目中，很多语法都不太明白如何使用了，如view.widthDime.equalTo()，这里的equalTo居然不能传参数

**Comment by youngsoft** [comment]
非常抱歉！因为各种原因swift版本一直后延。但是经过努力,昨天晚上发布了Swift版本:TangramKit, 您可以到https://github.com/youngsoft/TangramKit 中下载
