### ISSUE TITLE
相对布局中,最开始不给子视图设置约束,随后再给子视图设置约束时，子视图显示不正确

### ISSUE THREAD

**Issue by ZHJMrLu** [youngsoft/MyLinearLayout#90]

**Comment by youngsoft** [comment]
感谢发现这个BUG。这个BUG的原因是如果布局视图的子视图在第一次布局之前没有设置任何的约束，那么当布局执行完成后再设置约束将无效或者运行时会出现问题，原因是代码中获取约束对象处的逻辑写的有问题，目前在最新的1.7.0版本已经有修复。您可以下载最新的版本来解决这个问题。
