### ISSUE TITLE
UICollectionReusableView 在旋转中的问题

### ISSUE THREAD

**Issue by AppleDP** [youngsoft/MyLinearLayout#91]
在 ipad air 2 真机调试的时候，为多个 section 设置 section headerview，uicollectionviewcell 都是自适应高度，未旋转时第二个headerview会按 estimatedItemSize 的cell布局，旋转一次后会按自动适应的高度布局

**Comment by youngsoft** [comment]
不是很清楚您描述的问题，没有代码。是否可以贴出代码或者动图演示，或者您加QQ群：178573773 来具体将您的问题描述清楚。

**Comment by AppleDP** [comment]
出来的效果图：http://www.cocoachina.com/bbs/read.php?tid-1793352.html
