### ISSUE TITLE
UIScrollView 打开放大功能后旋转屏幕，scrollView 内的 layout 布局出现问题

### ISSUE THREAD

**Issue by AppleDP** [youngsoft/MyLinearLayout#93]
使用 scrollView 将 view 放大，将屏幕旋转后 scrollView 内的布局就出问题了

**Comment by youngsoft** [comment]
问题已经在1.8.0版本修复了。出现问题的原因是scrollView进行缩放的能力是通过transform属性来实现的。而且系统内部还动态调整了布局视图的center值，所以导致设置出现异常。
