### ISSUE TITLE
线性布局中子视图的相互依赖

### ISSUE THREAD

**Issue by AppleDP** [youngsoft/MyLinearLayout#94]
UIButton *zoneBtn = [UIButton buttonWithType:UIButtonTypeRoundedRect];
    
    UILabel *nameLab = [[UILabel alloc] initWithFrame:CGRectZero];
    
    UIButton *placeholderBtn = [UIButton buttonWithType:UIButtonTypeRoundedRect];
    placeholderBtn.backgroundColor = UIColor.redColor;
    
    MyLinearLayout *layout2 = [MyLinearLayout linearLayoutWithOrientation:MyOrientation_Horz];
    layout2.myCenterY = 0;
    layout2.backgroundColor = UIColor.yellowColor;
    layout2.myHorzMargin = 0;
    layout2.wrapContentHeight = YES;
    
    zoneBtn.myLeft = 20;
    zoneBtn.myCenterY = 0;
    zoneBtn.widthSize.equalTo(zoneBtn.widthSize).add(20);
    zoneBtn.heightSize.equalTo(zoneBtn.heightSize).add(3);
    
    nameLab.myCenterY = 0;
    nameLab.weight = 1.0;
    nameLab.heightSize.equalTo(nameLab.heightSize);
    
    placeholderBtn.myCenterY = 0;
    placeholderBtn.myRight = 20;
    placeholderBtn.widthSize.equalTo(zoneBtn.widthSize);
    placeholderBtn.heightSize.equalTo(zoneBtn.heightSize);

在线性布局中为子视图 placeholderBtn 添加 依赖zoneBtn的宽高 ，placeholderBtn的宽高依赖没有起作用

**Comment by youngsoft** [comment]
问题已经在1.8.0版本修复，这个版本增加了各种布局视图中子视图的依赖约束设置能力。
