### ISSUE TITLE
auto布局嵌套flowLayout布局,当flow高度变化时不能自动刷新auto高度

### ISSUE THREAD

**Issue by hbxfnsm** [youngsoft/MyLinearLayout#95]
MyFlowLayout *flow;
    // ...flow属性
    __weak typeof(MyFlowLayout *) weakFlow = flow;
    [flow setEndLayoutBlock:^{
        // 方式1
        [weakFlow setNeedsLayout];
        // 方式2
        // [weakFlow invalidateIntrinsicContentSize];
    }];
需要手动调用刷新才能刷新父视图(auto布局)的高度

**Comment by youngsoft** [comment]
问题已经修复，请升级到1.8.0版本。后续对布局视图中添加和删除子视图不再需要手动调用invalidateIntrinsicContentSize方法了。
