### ISSUE TITLE
textview高度自适应问题

### ISSUE THREAD

**Issue by x122536638** [youngsoft/MyLinearLayout#96]
textview高度等于contensize.height 如何实现啊,我看demo里还要设置代理,在代理里面 MyBaseLayout *layout = (MyBaseLayout*)textView.superview;
    [layout setNeedsLayout];感觉好麻烦啊

**Comment by x122536638** [comment]
需求是textview不能滚动,内容能全部显示,高度正好显示文本

**Comment by youngsoft** [comment]
目前来看你的需求好像用DEMO中介绍的方法就是最好的解决方案。既然textView不能滚动那么就意味着每次输入一个字都要重新计算高度，所以需要在代理里面进行布局刷新设置。如果嫌麻烦您可以试着封装一个控件，然后把一些逻辑实现在控件内部。然后外部使用者就不用再设置代理了(控件内部实现代理)。

**Comment by x122536638** [comment]
yeah
