### ISSUE TITLE
嵌套布局里面，无法点击Button

### ISSUE THREAD

**Issue by lamchaohao** [youngsoft/MyLinearLayout#98]
当一个viewController里view为MyLiearlayout rootLayout，此时再来一个Layout childLayout，并加入按钮到childLayout中，按钮点击无法接收到。这是怎么回事呢？

**Comment by youngsoft** [comment]
这个问题一般是有两种情况：1.你的childLayout的尺寸是0，2你的button的尺寸是0。虽然视图的宽高尺寸是0但是里面的文本还是能显示出来的，所以建议DEBUG一下视图树看看是哪个视图的尺寸为0导致的。 或者你把代码贴出来看看是哪里的约束设置得有问题。

**Comment by lamchaohao** [comment]
是的，属于第一种情况，childLayout的尺寸是0，但是可以显示。后面给childLayout加上frame后可以点击按钮了。谢谢🙏
