### ISSUE TITLE
使用相对布局居中视图时出现一个矛盾体~

### ISSUE THREAD

**Issue by szmichael-desgin** [youngsoft/MyLinearLayout#99]
#### 我在项目中遇到这样一个需求，见下图：

<img width="1078" alt="MyLayout居中视图矛盾01" src="https://user-images.githubusercontent.com/54985131/64425871-a5d51380-d0df-11e9-8d36-ca623cf9564a.png">

#### 效果展示：
<img width="433" alt="MyLayout居中视图矛盾02" src="https://user-images.githubusercontent.com/54985131/64425652-e54f3000-d0de-11e9-8b94-5931b118670f.png">

<img width="433" alt="MyLayout居中视图矛盾03" src="https://user-images.githubusercontent.com/54985131/64425663-ed0ed480-d0de-11e9-9b95-77081f32ee4c.png">

![MyLayout居中视图矛盾04](https://user-images.githubusercontent.com/54985131/64425670-f1d38880-d0de-11e9-99de-42bf984cc0e4.png)

```
留意：黄色背景视图和绿色背景视图。

紫色：UIScrollView
黄色：MyFrameLayout
绿色：线性布局视图
```

主要问题在于：隐藏和显示子视图后，黄色视图的高度计算存在问题。
默认状态 也有问题，MyFrameLayout 会偏离顶部一定距离，大概 20px。

![MyLayout居中视图矛盾05](https://user-images.githubusercontent.com/54985131/64425750-352df700-d0df-11e9-8986-0fa673cc519b.png)

**Comment by youngsoft** [comment]
您的问题在最新发布的1.9.0beta版本得到修复。
